name: wod_timer
description: "A WOD timer app for functional fitness workouts"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  audioplayers: ^6.1.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  go_router: ^14.8.1
  injectable: ^2.5.0
  json_annotation: ^4.9.0
  meta: ^1.16.0
  path_provider: ^2.1.5
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.3.5
  uuid: ^4.5.1

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  freezed: ^2.5.8
  injectable_generator: ^2.6.3
  json_serializable: ^6.9.4
  mocktail: ^1.0.4
  riverpod_generator: ^2.6.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
